# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: blackjack-software
google_analytics: dbyll
title: Blackjack Software

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Thoughts on coding, gaming, and other nerd stuff
author:
  name: Rosalind W.
  email: rosalind@blackjack-software.com
  github: blackjackkent
  twitter: blackjackkent
  pinterest: 
  linkedin: 
  bio: I'm a software dev who's been in the industry for over ten years, growing from a self-taught tinkerer in HTML to a specialist in Javascript, C#, and Android development.
  email_md5: 9a54d2d18db64b931e72527a15bbc4fa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
